[project]
name = "biolaysumm"
version = "0.1.0"
description = "Lay Summarization of Biomedical Research Articles and Radiology Reports @ BioNLP Workshop"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.6.0",
    "bert-score>=0.3.13",
    "datasets>=3.5.0",
    "evaluate>=0.4.3",
    "rouge-score>=0.1.2",
    "sacrebleu>=2.5.1",
    "unbabel-comet>=2.2.6",
]
